import React, { useState, useEffect } from 'react';
import { HelpCircle, ChevronDown, ChevronUp } from 'lucide-react';

export default function FAQ() {
  const [activeIndex, setActiveIndex] = useState(null);

  useEffect(() => {
    document.title = "FAQ & Help Center | EXIM Guru Mantra";
    window.scrollTo(0, 0);
  }, []);

  const faqData = [
    {
      q: "What is an Import Export Code (IEC) and who needs it?",
      a: "An Import Export Code (IEC) is a 10-digit registration identifier issued by the Director General of Foreign Trade (DGFT), Ministry of Commerce, Government of India. Any business or individual planning to import goods/services into India or export them out of India must possess a valid IEC. It is also required by customs authorities to clear shipments and by banks to process foreign exchange remittances."
    },
    {
      q: "How long does it take to get an IEC issued through DGFT?",
      a: "With our fast-track verification, we can compile your application, digital signature certificates (DSC), address proofs, and current account details to file the application on the DGFT portal instantly. In most cases, the DGFT issues the IEC certificate digitally within 24 hours of successful submission."
    },
    {
      q: "Which compliance schemes can save our business customs duties?",
      a: "Exporters can leverage several key government incentive schemes to maximize duty savings, including: \n• RoDTEP (Remission of Duties and Taxes on Exported Products)\n• Duty Drawback (DBK) claims under Section 74 or 75 of the Customs Act\n• EPCG (Export Promotion Capital Goods) scheme for zero-duty capital imports\n• Advance Authorization for duty-free raw material inputs.\nOur advisors can audit your product lines to match them with the most profitable schemes."
    },
    {
      q: "What is a GSTR reconciliation audit and why is it necessary?",
      a: "A GST Input Tax Credit (ITC) reconciliation involves comparing your Purchase Registers with GSTR-2B logs generated by suppliers. It is crucial to identify missing supplier invoices, correct mismatched tax rates, and prevent blocked credits. Under Section 16(4) of the CGST Act, reclaims without strict reconciliation can lead to heavy interest penalties."
    },
    {
      q: "How does EXIM Guru Mantra handle customs clearance and freight forwarding?",
      a: "We act as your end-to-end logistics partner. We coordinate customs broking, document preparation, and port clearance at all major air cargo terminals and sea ports in India. Combined with our sea & air freight forwarding services, we ensure compliance with FEMA, custom tariffs, and HSN classifications for a seamless transit."
    }
  ];

  const toggleAccordion = (idx) => {
    setActiveIndex(prev => prev === idx ? null : idx);
  };

  return (
    <div className="section" style={{ minHeight: '80vh', padding: '5rem 0' }}>
      <div className="container" style={{ maxWidth: '800px' }}>
        
        {/* Header */}
        <div className="section-header" style={{ marginBottom: '4rem', textAlign: 'center' }}>
          <span className="section-subtitle">Help Center</span>
          <h1 style={{ fontSize: '2.75rem', marginBottom: '1.25rem', color: 'var(--text-primary)' }}>
            Frequently Asked Questions
          </h1>
          <p className="section-desc" style={{ fontSize: '1.05rem', margin: '0 auto' }}>
            Get instant answers to common questions about trade licensing, customs clearance, taxation regulations, and company registration.
          </p>
        </div>

        {/* FAQ Accordion List */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          {faqData.map((item, idx) => {
            const isOpen = activeIndex === idx;
            return (
              <div 
                key={idx} 
                style={{
                  background: isOpen ? 'var(--bg-secondary)' : '#ffffff',
                  border: '1px solid var(--bg-tertiary)',
                  borderRadius: '8px',
                  overflow: 'hidden',
                  transition: 'all 0.3s ease'
                }}
              >
                {/* Question Trigger */}
                <button
                  onClick={() => toggleAccordion(idx)}
                  style={{
                    width: '100%',
                    padding: '1.5rem 2rem',
                    background: 'none',
                    border: 'none',
                    textAlign: 'left',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: '1.5rem',
                    outline: 'none'
                  }}
                >
                  <span style={{ 
                    fontSize: '1.05rem', 
                    fontWeight: 700, 
                    color: isOpen ? 'var(--primary)' : 'var(--text-primary)',
                    fontFamily: 'var(--font-heading)',
                    transition: 'color 0.25s ease'
                  }}>
                    {item.q}
                  </span>
                  {isOpen ? (
                    <ChevronUp size={18} style={{ color: 'var(--primary)', flexShrink: 0 }} />
                  ) : (
                    <ChevronDown size={18} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />
                  )}
                </button>

                {/* Answer Content */}
                {isOpen && (
                  <div style={{
                    padding: '0 2rem 1.5rem 2rem',
                    color: 'var(--text-secondary)',
                    fontSize: '0.95rem',
                    lineHeight: '1.7',
                    borderTop: '1px solid var(--bg-tertiary)',
                    paddingTop: '1.25rem',
                    whiteSpace: 'pre-line'
                  }}>
                    {item.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Contact CTA */}
        <div style={{
          marginTop: '4rem',
          textAlign: 'center',
          background: 'var(--bg-secondary)',
          border: '1px solid var(--bg-tertiary)',
          borderRadius: '12px',
          padding: '2.5rem'
        }}>
          <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem', fontWeight: 800 }}>Still Have Questions?</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.92rem', marginBottom: '1.5rem' }}>
            Our corporate consulting panel is standing by to assist with your specific customs and taxation inquiries.
          </p>
          <a href="/contact" className="btn btn-primary" style={{ padding: '0.65rem 1.75rem', display: 'inline-flex', gap: '0.5rem', alignItems: 'center' }}>
            <HelpCircle size={16} />
            <span>Ask Our Experts</span>
          </a>
        </div>

      </div>
    </div>
  );
}
